version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
